import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className= {styles.navbar}>
          <h3 className= {styles.logo}>Gaurav</h3>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/services">Services</Link></li>
            <li><Link href="/contact">Contact</Link></li>
          </ul>
        </div>
      <main className={styles.main}>
       <div className={styles.homeContainer}>
         <h2>Welcome To The Coding World.</h2>
          <h4>Do Love With Coding</h4>
          <button>Gaurav Gupta</button>
       </div>
      </main>

      <footer className={styles.footer}>
          <span >Powered by Gaurav</span>
      </footer>
    </div>
  )
}
